"use client";

import { useEffect, useState } from "react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import AppNavbar from "@/components/AppNavbar";
import { API_URL, getErrorMessage, getToken } from "@/lib/api";

type Metrics = {
  accuracy: number;
  precision: number;
  recall: number;
  f1_score: number;
  labels: string[];
  confusion_matrix: number[][];
};

export default function AccuracyPage() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [authChecked, setAuthChecked] = useState(false);

  useEffect(() => {
    async function loadMetrics() {
      try {
        const token = getToken();

        if (!token) {
          window.location.replace("/login");
          return;
        }

        setAuthChecked(true);

        const res = await fetch(`${API_URL}/metrics/model`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        const data = await res.json();

        if (!res.ok) {
          setError(getErrorMessage(data, "Could not load metrics."));
          setLoading(false);
          return;
        }

        setMetrics(data);
      } catch {
        setError("Failed to fetch metrics. Make sure FastAPI backend is running.");
      } finally {
        setLoading(false);
      }
    }

    loadMetrics();
  }, []);

  if (!authChecked) {
    return (
      <main className="auth-wrap">
        <div className="card auth-card">
          <span className="badge">Checking secure access</span>
          <h2>Loading metrics...</h2>
        </div>
      </main>
    );
  }

  const chartData = metrics
    ? [
        {
          name: "Accuracy",
          value: Number((metrics.accuracy * 100).toFixed(2)),
        },
        {
          name: "Precision",
          value: Number((metrics.precision * 100).toFixed(2)),
        },
        {
          name: "Recall",
          value: Number((metrics.recall * 100).toFixed(2)),
        },
        {
          name: "F1 Score",
          value: Number((metrics.f1_score * 100).toFixed(2)),
        },
      ]
    : [];

  return (
    <main className="container dashboard">
      <AppNavbar />

      <section className="card">
        <span className="badge">Model Accuracy Documentation</span>

        <h1 style={{ fontSize: 46 }}>AI Model Performance</h1>

        <p>
          This secure page displays validation metrics generated by the FastAPI
          ML pipeline and stored in MongoDB.
        </p>
      </section>

      {loading && (
        <section className="card" style={{ marginTop: 18 }}>
          <p>Loading metrics...</p>
        </section>
      )}

      {error && (
        <section className="card" style={{ marginTop: 18 }}>
          <p className="error">{error}</p>
        </section>
      )}

      {metrics && (
        <>
          <section className="grid-4" style={{ marginTop: 18 }}>
            <div className="metric">
              <span>Accuracy</span>
              <b>{(metrics.accuracy * 100).toFixed(1)}%</b>
            </div>

            <div className="metric">
              <span>Precision</span>
              <b>{(metrics.precision * 100).toFixed(1)}%</b>
            </div>

            <div className="metric">
              <span>Recall</span>
              <b>{(metrics.recall * 100).toFixed(1)}%</b>
            </div>

            <div className="metric">
              <span>F1 Score</span>
              <b>{(metrics.f1_score * 100).toFixed(1)}%</b>
            </div>
          </section>

          <section className="workspace" style={{ marginTop: 18 }}>
            <div className="card">
              <h2>Performance Metrics</h2>

              <p>
                The chart compares the main classification metrics of the
                resume fit prediction model.
              </p>

              <ResponsiveContainer width="100%" height={340}>
                <BarChart
                  data={chartData}
                  margin={{
                    top: 20,
                    right: 20,
                    left: 0,
                    bottom: 10,
                  }}
                >
                  <defs>
                    <linearGradient
                      id="metricGradient"
                      x1="0"
                      y1="0"
                      x2="0"
                      y2="1"
                    >
                      <stop offset="0%" stopColor="#60a5fa" />
                      <stop offset="100%" stopColor="#8b5cf6" />
                    </linearGradient>
                  </defs>

                  <CartesianGrid
                    stroke="rgba(255,255,255,0.08)"
                    strokeDasharray="4 4"
                    vertical={false}
                  />

                  <XAxis
                    dataKey="name"
                    tick={{
                      fill: "#aab8cc",
                      fontSize: 13,
                    }}
                  />

                  <YAxis
                    domain={[0, 100]}
                    tick={{
                      fill: "#aab8cc",
                      fontSize: 13,
                    }}
                    tickFormatter={(value) => `${value}%`}
                  />

                  <Tooltip
                    cursor={false}
                    contentStyle={{
                      background: "rgba(15,23,42,0.96)",
                      border: "1px solid rgba(255,255,255,0.12)",
                      borderRadius: "14px",
                      color: "#eef5ff",
                      boxShadow: "0 18px 45px rgba(0,0,0,0.35)",
                    }}
                    labelStyle={{
                      color: "#cbd5e1",
                    }}
                    itemStyle={{
                      color: "#7dd3fc",
                    }}
                    formatter={(value) => [`${value}%`, "Score"]}
                  />

                  <Bar
                    dataKey="value"
                    fill="url(#metricGradient)"
                    radius={[12, 12, 0, 0]}
                    barSize={56}
                    activeBar={false}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className="card">
              <h2>Confusion Matrix</h2>

              <p>
                Rows represent actual labels; columns represent predicted
                labels.
              </p>

              <div style={{ overflowX: "auto", marginTop: 20 }}>
                <table
                  style={{
                    width: "100%",
                    borderCollapse: "collapse",
                  }}
                >
                  <thead>
                    <tr>
                      <th style={thStyle}>Actual Label</th>

                      {metrics.labels.map((label) => (
                        <th key={label} style={thStyle}>
                          {label}
                        </th>
                      ))}
                    </tr>
                  </thead>

                  <tbody>
                    {metrics.confusion_matrix.map((row, rowIndex) => (
                      <tr key={metrics.labels[rowIndex]}>
                        <td style={tdStyle}>{metrics.labels[rowIndex]}</td>

                        {row.map((value, columnIndex) => (
                          <td key={columnIndex} style={tdStyle}>
                            <span
                              style={{
                                display: "inline-flex",
                                alignItems: "center",
                                justifyContent: "center",
                                minWidth: 38,
                                height: 34,
                                borderRadius: 12,
                                background:
                                  rowIndex === columnIndex
                                    ? "rgba(52,211,153,0.16)"
                                    : "rgba(125,211,252,0.10)",
                                color:
                                  rowIndex === columnIndex
                                    ? "#34d399"
                                    : "#eef5ff",
                                fontWeight: 900,
                              }}
                            >
                              {value}
                            </span>
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </section>
        </>
      )}
    </main>
  );
}

const thStyle: React.CSSProperties = {
  padding: "14px 12px",
  borderBottom: "1px solid rgba(255,255,255,0.14)",
  color: "#eef5ff",
  textAlign: "left",
  fontSize: 14,
};

const tdStyle: React.CSSProperties = {
  padding: "14px 12px",
  borderBottom: "1px solid rgba(255,255,255,0.10)",
  color: "#cbd5e1",
  fontSize: 14,
};
